Wr/sfdx ify
salesforcecli/plugin-settings pull request #195
Opened 2023-02-10 18:59 UTC by WillieRuemmele

### What does this PR do?
incorporates `sfdx` behavior/json/config values so that `plugin-settings` can replace `plugin-config` and `plugin-alias`
### What issues does this PR fix or reference?
@W-12083531@

2023-02-14 21:19 UTC, shetzel approved these changes

2023-02-14 21:19 UTC, shetzel commented on src/commands/alias/set.ts
> +          this.warn(`Setting an alias to undefined is deprecated v58.0. Use ${this.config.bin} alias unset instead.`);
Should this be, "deprecated as of v57.0."?

2023-02-14 22:19 UTC, peternhale requested changes

2023-02-14 22:19 UTC, peternhale commented on src/commands/config/list.ts
>    public static flags = {};
Do we need flags?

2023-02-14 22:19 UTC, peternhale commented on src/commands/config/unset.ts
>      } else {
Don't need the else

2023-02-14 22:19 UTC, peternhale commented on src/commands/config/unset.ts
>        if (!this.jsonEnabled()) {
Don't need the guard for !json

2023-02-14 22:19 UTC, peternhale commented on src/config.ts
> +  public calculateSuggestion(cmd: string): string {
Am I mistaken, but this is being used to get suggestions for config keys. Suggest changing `cmd` to something more fitting.

2023-02-15 13:20 UTC, peternhale requested changes

2023-02-15 13:20 UTC, peternhale commented on src/commands/alias/list.ts
> +  public static readonly flags = { loglevel };
In order to get any warnings regarding loglevel parse must be called

2023-02-15 13:20 UTC, peternhale commented on src/commands/alias/set.ts
> +  public static readonly flags = { loglevel };
ditto

2023-02-22 22:49 UTC, shetzel commented
**QA Results**

**Alias:list**
✅  bin/run alias list --help
✅  bin/run alias list
✅  bin/run alias list --json
✅  Compare output with sfdx alias plugin
✅  Aliases work: force alias list, alias list, force:alias:list, alias:list

**Alias:set**
✅  bin/run alias set --help
✅  bin/run alias set foo=bar
✅  bin/run alias set foo="bar bar"
✅  bin/run alias set foo=
✅  bin/run alias set foo bar
✅  bin/run alias set
✅  bin/run alias set foo=bar --json --> has additional entry in result for `"success": true` which is fine
✅  Aliases work: force alias set, alias set, force:alias:set, alias:set

**Alias:unset**
✅  bin/run alias unset --help
✅  bin/run alias unset foo
✅  bin/run alias unset foo bar
✅  bin/run alias unset
✅  bin/run alias unset foo --json  --> has additional entry for `"value": "old value"` and `"success": true` which is fine
✅  bin/run alias set --all
✅  bin/run alias set --all -p
✅  Aliases work: force alias unset, alias unset, force:alias:unset, alias:unset

**Config:list**
✅  bin/run config list --help
✅  bin/run config list
✅  bin/run config list --json  --> has additional entry for `"name": "target-org"` and `"success": true` which is fine
✅  Aliases work: force config list, config list, force:config:list, config:list

**Config:get**
✅  bin/run config get --help
✅  bin/run config get instanceurl  --> "did you mean?"
✅  bin/run config get defaultusername --> warn
✅  bin/run config get target-org
✅  bin/run config get --json  --> has additional entries, all of which are fine
✅  Aliases work: force config get, config get, force:config:get, config:get

**Config:set**
✅  bin/run config set --help
✅  bin/run config set instance-url  --> "did you mean?"
✅  bin/run config set defaultusername --> warn
✅  bin/run config set target-org
❌  bin/run config set org-instance-url --json  --> Different json structure
❌  bin/run config set instanceurl --json  --> incorrect status and success values (should fail)
✅  Aliases work: force config set, config set, force:config:set, config:set


**Config:unset**
✅  bin/run config unset --help
❌  bin/run config unset instance-url  --> "did you mean?" Failed.  It suggested the deprecated key, I selected it and an error was thrown.
✅  bin/run config unset defaultusername --> warn
✅  bin/run config unset target-org
❌  bin/run config unset target-org --json  --> Different json structure
✅  Aliases work: force config unset, config unset, force:config:unset, config:unset

plugin-config results in current latest-rc of sfdx:
<img width="912" alt="Screenshot 2023-02-22 at 3 19 27 PM" src="https://user-images.githubusercontent.com/2703995/220777785-f52e258d-2d94-4a89-b06f-16eb208decc7.png">

plugin-settings results:
<img width="1228" alt="Screenshot 2023-02-22 at 3 21 51 PM" src="https://user-images.githubusercontent.com/2703995/220777937-cd63b9c8-45b8-4635-8903-68da3651f13a.png">
<img width="1083" alt="Screenshot 2023-02-22 at 3 30 34 PM" src="https://user-images.githubusercontent.com/2703995/220777963-1fed78ad-17f5-4484-ad10-ae22b74ca801.png">

2023-03-02 00:16 UTC, merged