fix: warn when attempting to unset a global config without flag
salesforcecli/plugin-settings pull request #346
Opened 2023-08-07 20:14 UTC by WillieRuemmele

### What does this PR do?
warns when attempting to unset a global config without the `--global` flag because the output is confusing
### What issues does this PR fix or reference?
@W-13825061@

2023-08-08 15:46 UTC, jshackell-sfdc approved these changes
One small edit, but approving anyway 'cause I know you'll deal with it :)

2023-08-08 15:46 UTC, jshackell-sfdc commented on messages/config.unset.md
> +The %s config is still set globally, unset it by using the --global flag.
```suggestion
The %s config variable is still set globally, unset it by using the --global flag.
```

2023-08-08 15:46 UTC, jshackell-sfdc commented on messages/config.unset.md
> +The %s config is still set globally, unset it by using the --global flag.
We use "config variable" in the docs: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_dev_cli_config_values.htm

2023-08-10 17:05 UTC, shetzel requested changes

2023-08-10 17:05 UTC, shetzel commented on src/commands/config/unset.ts
> +          // if the user wanted to unset a global value, and it's not in the global, warn them
This comment is confusing to me, particularly the "and it's not in the global" part.  What do you think about wording it this way?
```suggestion
          // If the config var is still set globally after an unset and the user didn't have the `--global` flag set, warn them.
```

2023-08-10 19:10 UTC, shetzel approved these changes

2023-08-10 19:28 UTC, shetzel commented
QA:
✅ - unset local only
✅ - unset global only
✅ - unset local (with nothing set) with global still there.  warns about the global still being set.
✅ - unset local (with it set) with global still there.  warns about the global still being set.

2023-08-10 20:23 UTC, merged